version: "3.7"
services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    networks:
      - fullstack

  server:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8000:8000"
    networks:
      - fullstack
    #volumes:
    #  - .:/go/src/github.com/reinnatan/linkaja
    #working_dir: /go/src/github.com/reinnatan/linkaja

networks:
  fullstack:
    driver: bridge
    